api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from api import ajax
from api.views import PurchaseViewSet


router = DefaultRouter()
router.register(r'purchases', PurchaseViewSet, basename='purchases'),


urlpatterns = [
    path('', include(router.urls)),
    path("favorites", ajax.add_favorites, name="add_favorites"),
    path("favorites/<int:recipe_id>/",
         ajax.remove_favorites, name="remove_favorites"),
    path("ingredients/", ajax.found_ingredient, name="found_ingredient"),
    path("subscriptions", ajax.add_subscription, name="add_subscription"),
    path("subscriptions/<int:author_id>/",
         ajax.remove_subscription, name="remove_subscription"),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('recipes.urls')),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path('about/', include('django.contrib.flatpages.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "foodgram.errors.page_not_found"  # noqa
handler500 = "foodgram.errors.server_error"  # noqa

recipes/models.py
from django.contrib.auth import get_user_model
from django.db.models import UniqueConstraint
from django.core.validators import MinValueValidator
from django.db import models

User = get_user_model()


class Tag(models.Model):
    """Model tags."""
    title = models.CharField('Имя тега', max_length=60, db_index=True)
    display_name = models.CharField('Имя тега для шаблона', max_length=60)
    color = models.CharField('Цвет тега', max_length=15)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.title


class Recipe(models.Model):
    """Model recipes."""
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор публикации')
    title = models.CharField(
        max_length=100,
        verbose_name='Название'
    )
    description = models.TextField(
        null=True, verbose_name='Описание'
    )
    ingredients = models.ManyToManyField(
        'Ingredient',
        through='Quantity',
        through_fields=('recipe', 'ingredient'),
        verbose_name='Ингредиенты', blank=True
    )
    image = models.ImageField(
        upload_to='recipes/',
        null=True,
        verbose_name="Картинка"
    )
    tags = models.ManyToManyField(Tag, verbose_name='Тег',
                                  related_name='recipes')
    time = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        verbose_name='Время приготовления'
    )
    pub_date = models.DateTimeField(
        auto_now=True,
        db_index=True,
        verbose_name="Дата публикации"
    )

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    """Model ingredients."""
    title = models.CharField(
        max_length=100,
        verbose_name='Название'
    )
    dimension = models.CharField(
        max_length=100,
        verbose_name='Мера',
    )

    class Meta:
        verbose_name = 'Ингридиент'
        verbose_name_plural = 'Ингридиенты'

    def __str__(self):
        return f"{self.title} ({self.dimension})"


class Quantity(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE,
                                   verbose_name='Ингредиент')
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               verbose_name='Рецепт')
    amount = models.PositiveIntegerField(verbose_name='Количество')

    class Meta:
        verbose_name = 'Количество'


class Follow(models.Model):
    """Model for subscribe."""
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following"
    )

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"
        ordering = ('author',)
        constraints = [
            UniqueConstraint(
                fields=["user", "author"],
                name='unique_follow')]


class Purchase(models.Model):
    """Model our purchase."""
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='purchases',
                             verbose_name='Пользователь')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name='purchases',
                               verbose_name='Рецепт')

    class Meta:
        verbose_name = 'Покупки'


class Favorite(models.Model):
    """Model favorites recipes."""
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='favorites',
                             verbose_name='Пользователь')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name='favorites',
                               verbose_name='Понравившейся рецепт')

    class Meta:
        verbose_name = 'Избранное'
        constraints = [
            UniqueConstraint(
                fields=["user", "recipe"],
                name='unique_favorite')]

templates/base.html
<!doctype html>
<html>
    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}Заголовок страницы{% endblock %}</title>
        {% block static %}

        {% endblock %}

    </head>

    <body>
    {% include 'includes/nav.html' %}

        <main class="main container">
            {% block content %}

            {% endblock %}
        </main>

    {% include 'includes/footer.html' %}

    {% block script %}

    {% endblock %}

    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %} Рецепты {% endblock %}
{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block content %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Рецепты</h1>
        <ul class="tags">
            {% include "includes/tags.html" %}
        </ul>
    </div>
    <div class="card-list">
        {% for recipe in page %}
            {% include "recipes/recipe_item.html" with recipe=recipe %}
        {% endfor %}
    </div>
    {% if page.has_other_pages %}
        {% include "includes/paginator.html" with items=page paginator=paginator %}
    {% endif %}
</main>
{% endblock %}

{% block script %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    {% if user.is_authenticated %}
        <script src="{% static 'indexAuth.js' %}"></script>
    {% else %}
        <script src="{% static 'indexNotAuth.js' %}"></script>
    {% endif %}
{% endblock %}

templates/new.html
{% extends "base.html" %} 
{% block title %}{{ title_text }}{% endblock %}

{% load user_filters %}

{% load static %}
{% block static %}
	<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">
            {% if recipe %}
                Редактирование рецепта
            {% else %}
                Создание рецепта
            {% endif %}
        </h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="{{ form.title.id_for_label }}" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            <input type="checkbox" name="tags" value="breakfast" id="id_breakfast"
                                   class="tags__checkbox tags__checkbox_style_orange"
                                   {% if 'breakfast' in tags %}checked{% endif %}>
                            <label for="id_breakfast" class="tags__label">Завтрак</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="tags" value="lunch" id="id_lunch"
                                   class="tags__checkbox tags__checkbox_style_green"
                                   {% if 'lunch' in tags %}checked{% endif %}>
                            <label for="id_lunch" class="tags__label">Обед</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="tags" value="dinner" id="id_dinner"
                                   class="tags__checkbox tags__checkbox_style_purple"
                                   {% if 'dinner' in tags %}checked{% endif %}>
                            <label for="id_dinner" class="tags__label">Ужин</label>
                        </div>
                    </div>
                    <span class="form__error">{{ form.tags.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="1">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                        {% if ingredients %}
                            {% for ingredient in ingredients %}
                                <div class="form__field-item-ingredient" id="ing_{{ ingredient.ingredient.id }}"><span>
										{{ ingredient.ingredient.title }} {{ ingredient.amount }}
                                    {{ ingredient.ingredient.dimension }}</span> <span
                                        class="form__field-item-delete"></span>
                                    <input id="nameIngredient_{{ ingredient.ingredient.id }}"
                                           name="nameIngredient_{{ ingredient.ingredient.id }}" type="hidden"
                                           value="{{ ingredient.ingredient.title }}">
                                    <input id="valueIngredient_{{ ingredient.ingredient.id }}"
                                           name="valueIngredient_{{ ingredient.ingredient.id }}" type="hidden"
                                           value="{{ ingredient.amount }}">
                                    <input id="unitsIngredient_{{ ingredient.ingredient.id }}"
                                           name="unitsIngredient_{{ ingredient.ingredient.id }}" type="hidden"
                                           value="{{ ingredient.ingredient.dimension }}">
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    {% if form.errors %}
                    {% for error in form.non_field_errors %}
                    <div class="form__group">
                    <span class="form__error">{{ error|escape }}</span>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.time|addclass:"form__input" }}
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error">{{ form.time.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description|addclass:"form__textarea" }}
                    <span class="form__error">{{ form.description.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label"> Загрузить фото </span>
                <div class="form__field-group">
                    {{ form.image }}
                <span class="form__error"></span>
            </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">
                    {% if recipe %}
                        Сохранить
                    {% else %}
                        Создать рецепт
                    {% endif %}
                </button>
                {% if recipe %}
                    <a style="margin-left: 2.5em" href="{% url 'delete_recipe' recipe.author.username recipe.id %}"
                       class="form__ingredient-link">Удалить</a>
                {% endif %}
            </div>
        </form>
    </div>

{% endblock %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}